name: Publish docs

on:
  workflow_dispatch

jobs:
  build-and-publish-docs:
    name: Build and publish docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build docs
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade --upgrade-strategy eager -e .[dev]
          mkdocs build

      - name: Publish docs
<<<<<<< HEAD
        uses: JamesIves/github-pages-deploy-action@v4.3.3
=======
        uses: JamesIves/github-pages-deploy-action@v4.4.0
>>>>>>> 75e79a1c5940534d9d81e0a28399730fb01f6c4f
        with:
          branch: docs
          folder: site
